from lastfm.methods.album import Album  # noqa
from lastfm.methods.auth import Auth  # noqa
from lastfm.methods.chart import Chart  # noqa
from lastfm.methods.geo import Geo  # noqa
from lastfm.methods.library import Library  # noqa
from lastfm.methods.tag import Tag  # noqa
from lastfm.methods.user import User  # noqa
from lastfm.methods.artist import Artist  # noqa
from lastfm.methods.track import Track  # noqa
